# Appearance
title: Shane Krolikowski
description: This is my personal website. I am a programmer from Seattle.
author: skrolikowski
logo: /assets/me.png
location: Seattle, WA - 98119

# Theme
# theme: jekyll-swiss
# theme_color: black

# GitHub
github_username: skrolikowski
github_repo: skrolikowski.github.io

# Social Media
social:
  name: skrolikowski
  links:
    - https://github.com/skrolikowski
    - https://www.instagram.com/shanekrolikowski/
    - https://www.reddit.com/user/skrolikowski
    - https://www.linkedin.com/in/skrolikowski/

# Outputting
url: shanekrolikowski.com
base_url: /
permalink: /:categories/:year/:month/:day/:title
paginate_path: /page:num
# timezone: America/Los_Angeles

# Blogs
show_drafts: false                # Process and render draft posts.
future: false                     # Publish posts or collection documents with a future date.
unpublished: false                # Render posts that were marked as unpublished.
lsi: true                         # Produce an index for related posts.
limit_posts: 0                    # Limit the number of posts to parse and publish.

# Collections
collections_dir: collections
collections:
  algorithms:
    output: true
    permalink: /:collection/:title
  challenges:
    output: true
    permalink: /:collection/:title


# Performance
incremental: true          # Enable the experimental incremental build feature.
profile: true              # Generate a Liquid rendering profile to help you identify performance bottlenecks.
strict_front_matter: true  # Cause a build to fail if there is a YAML syntax error in a page's front matter.

# Plugins
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap