# Appearance
title: Shane Krolikowski
description: This is my personal website. I am a programmer from Seattle.
author: skrolikowski
location: Seattle, WA - 98119

# GitHub
github_username: skrolikowski
github_repo: skrolikowski.github.io

# Social Media
social:
  name: skrolikowski
  links:
    - https://github.com/skrolikowski
    - https://www.instagram.com/shanekrolikowski/
    - https://www.reddit.com/user/skrolikowski
    - https://www.linkedin.com/in/skrolikowski/

# Outputting
url: shanekrolikowski.com
base_url: /
permalink: pretty
paginate_path: /page:num
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true

# Blogs
show_drafts: false                # Process and render draft posts.
future: false                     # Publish posts or collection documents with a future date.
unpublished: false                # Render posts that were marked as unpublished.
lsi: true                         # Produce an index for related posts.
limit_posts: 0                    # Limit the number of posts to parse and publish.

# Collections
collections_dir: collections
collections:
  projects:
    output: true
    permalink: /:collection/:categories/:title
  science:
    output: true
    permalink: /:collection/:title
  tutorials:
    output: true
    permalink: /:collection/:title


# Performance
incremental: false         # Enable the experimental incremental build feature.
profile: true              # Generate a Liquid rendering profile to help you identify performance bottlenecks.
strict_front_matter: true  # Cause a build to fail if there is a YAML syntax error in a page's front matter.

# Plugins
plugins:
  - jemoji
  - rouge
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap